### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by ovpn-to** [bauerj/OCHproxy#11]
10.42.10.3 - - [06/Aug/2015 17:08:09] "GET /get?link=http%3A%2F%2Fuploaded.net%2Ffile%2F0lwwkv68%2F*.rar&user=*&password=* HTTP/1.1" 200 -
    Opening connection to http://www.debriditalia.com/*.rar
    opening http://www.debriditalia.com/*.rar
    Copying file to client
    ----------------------------------------
    Exception happened during processing of request from ('10.42.10.3', 57046)
    Traceback (most recent call last):
      File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
        self.finish_request(request, client_address)
      File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
        self.RequestHandlerClass(request, client_address, self)
      File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
        self.finish()
      File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
        self.wfile.close()
      File "/usr/lib/python2.7/socket.py", line 279, in close
        self.flush()
      File "/usr/lib/python2.7/socket.py", line 303, in flush
        self._sock.sendall(view[write_offset:write_offset+buffer_size])
    error: [Errno 32] Broken pipe
    ----------------------------------------

**Comment by ovpn-to** [comment]
error: [Errno 104] Connection reset by peer

https://paste.d0wn.biz/55c4bd83dd.txt

**Comment by bauerj** [comment]
This looks like a client error so I need a bit more context here.

 - Does this happen only for links that use the debriditalia plugin?
 - Is there some kind of reverse proxy (haproxy, nginx) between OCHproxy and the client?
 - Did you abort the download before it completed?
 - Did you trim the log in any way? The messages look like debugging is enabled but the message format seems wrong.

My guess is that the user (e.g. the one downloading the file) aborted the download (in case of error 104) or there are connection problems (in case of error 32).

**Comment by ovpn-to** [comment]
Does this happen only for links that use the debriditalia plugin?
- dont know

Is there some kind of reverse proxy (haproxy, nginx) between OCHproxy and the client?
- haproxy

Did you abort the download before it completed?
- it wasnt me

Did you trim the log in any way? The messages look like debugging is enabled but the message format seems wrong.
- censored filename by * wildcard

**Comment by bauerj** [comment]
> Did you abort the download before it completed?
>>  it wasnt me

Then I suppose that's what's happening here.

I suggest that I try to change the error message into something more clear and compact and make sure that it only appears in debug mode.
