### ISSUE TITLE
strip 1 in username and password?

### ISSUE THREAD

**Issue by twink0r** [bauerj/OCHproxy#9]
u, p = x.strip().split(":", 1)

I dont understand this line ;)

**Comment by bauerj** [comment]
For each line in users.txt:


1. Remove whitespaces at the end and at the beginning.
2. Split the result at the first ocurrence of `:`. That's necessary if your password contains a `:`. The username must not contain a `:`.

**Comment by bauerj** [comment]
That means:

The users file could look like this:


    user1:super secret password.   
    user2::

**Comment by twink0r** [comment]
If you use test1 as password and try to use test1 you get a error 401!

**Comment by bauerj** [comment]
Can't reproduce that:

    ...\PycharmProjects\OCHproxy [master]> get-content users.txt
	test1:test1
	...\PycharmProjects\OCHproxy [master]> curl "http://localhost:81/get?link=http%3A%2F%2Fg
	et.testfile%2F&user=test1&password=test1"


	StatusCode        : 200
	StatusDescription : OK
	Content           : {177, 229, 146, 39...}
	RawContent        : HTTP/1.0 200 OK
	                    Connection: close
	                    Accept-Ranges: bytes
	                    Content-Length: 1000000
	                    Content-Type: application/octet-stream
	                    Date: Mon, 13 Jul 2015 12:14:36 GMT
	                    Last-Modified: Wed, 15 Feb 2012 02:39:52...
	Headers           : {[Connection, close], [Accept-Ranges, bytes], [Content-Length, 1000000], [Content-Type,
	                    application/octet-stream]...}
	RawContentLength  : 1000000

**Comment by bauerj** [comment]
Although there is a bug where the password gets used as the username and vice-versa. Maybe that's the real issue you run into here?

**Comment by bauerj** [comment]
Of course I need to write a documentation on this as well as directions on how to get it working.

That's going to happen as soon as I update the plugin API.

**Comment by twink0r** [comment]
http://XXX:XXX.XXX.XX:8080/get?link=test.de%2Ftest.png&user=test&password=test1

GET /get?link=test.de%2Ftest.png&user=test&password=test1 HTTP/1.1
Host: 158.58.170.6:8080
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Connection: keep-alive

HTTP/1.0 401 Unauthorized
----------------------------------------------------------

root@idontknow:/home/OCHproxy# cat users.txt
test:test1

**Comment by bauerj** [comment]
git log --pretty -n 1
    commit 02048f41218b08b2a6a4a37e3ee3e95042ff088b

Can you confirm that?

**Comment by twink0r** [comment]
root@idontknow:/home/OCHproxy# git log --pretty -n 1
commit 8143e44bc339cb55987cd4adbbd87dc0f85e623a
Author: Johann Bauer <bauerj@bauerj.eu>
Date:   Sun Jul 12 22:40:39 2015 +0200

    Change to new-style classes

**Comment by bauerj** [comment]
Okay, then that's the issue here.

Please do a `git pull`.

**Comment by twink0r** [comment]
git pull done 
restarted and it works ;) Perfect !
